language: cpp
compiler:
    - gcc
    - clang
before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test     # gcc 4.8
    - sudo apt-add-repository -y ppa:zoogie/sdl2-snapshots       # libsdl2
    - sudo apt-add-repository -y ppa:kubuntu-ppa/backports       # cmake 2.8 stuff
    - sudo apt-get update
install:
    - sudo apt-get install libglew-dev libglm-dev libsdl2-dev
    - sudo apt-get install cmake
before_script:
    - mkdir build
    - cd build
    - cmake ${CMAKE_ARGS} ..
script: make
after_success:
    - echo Done!
env:
    - CMAKE_ARGS=""
branches:
    only:
        - master
notifications:
    email:
        on_success: change
        on_failure: always
os:
    - linux
