language: cpp
compiler:
    - gcc
    - clang
before_install:
    - wget http://libsdl.org/release/SDL2-2.0.3.tar.gz -O - | tar xz
    - (cd SDL2-2.0.3 && ./configure --prefix=$PREFIX && make -j5 && sudo make install)
    - sudo apt-add-repository ppa:kalakris/cmake
    - sudo apt-get update
install:
    - sudo apt-get install libglew-dev libglm-dev
    - sudo apt-get install cmake
before_script:
    - mkdir build
    - cd build
    - cmake ${CMAKE_ARGS} ..
script: make
after_success:
    - echo Done!
env:
    - CMAKE_ARGS=""
branches:
    only:
        - master
notifications:
    email:
        on_success: change
        on_failure: always
os:
    - linux
